name: Build podman for ubuntu
concurrency: aws-worker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish-podman.yml'
      - 'containers/podman-ubuntu/**/*'

env:
  GO_LANG_VERSION: '1.17'
  CONMON_VERSION: '2.1.3'
  CNI_PLUGINS_VERSION: '1.1.1'
  RUNC_VERSION: '1.1.3'
  PODMAN_VERSION: '4.2.0'

  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_X86_IMAGE_ID: ${{ secrets.AWS_X86_IMAGE_ID }}
  AWS_ARM64_IMAGE_ID: ${{ secrets.AWS_ARM64_IMAGE_ID }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build:
    name: Build & upload packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      x86_builder_id: ${{ steps.launch_instances.outputs.x86_builder_id }}
      arm_builder_id: ${{ steps.launch_instances.outputs.arm_builder_id }}
    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Launch instances
        id: launch_instances
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        run: |
          ./scripts/launch-builders.sh
      -
        name: Build packages
        continue-on-error: true
        env:
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          X86_BUILDER_IP: ${{ steps.launch_instances.outputs.x86_ip }}
          ARM_BUILDER_IP: ${{ steps.launch_instances.outputs.arm_ip }}
        run: |
          ./scripts/setup-remote-builder.sh
          ./containers/podman-ubuntu/build.sh
      -
        name: Archive packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: containers/podman-ubuntu/packages
      -
        name: Terminate instances
        if: ${{ always() && steps.launch_instances.outcome == 'success' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_X86_BUILDER_ID: ${{ steps.launch_instances.outputs.x86_builder_id }}
          AWS_ARM_BUILDER_ID: ${{ steps.launch_instances.outputs.arm_builder_id }}
        run: |
          ./scripts/stop-builders.sh
